/*
 * DO NOT EDIT!
 * Generated by msgpack-pjsekai dump.cs compiler version 0.4.0.
 * source: dump.cs
 */

#ifndef MSGPACK_PJSEKAI_BRIDGE_GENERATED_H
#define MSGPACK_PJSEKAI_BRIDGE_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct mpj_buffer {
    uint8_t *data;
    size_t size;
} mpj_buffer;

typedef struct mpj_value mpj_value;

enum {
    MPJ_KEY_STRING = 0,
    MPJ_KEY_INT = 1
};

enum {
    MPJ_VALUE_NIL = 0,
    MPJ_VALUE_BOOL = 1,
    MPJ_VALUE_INT = 2,
    MPJ_VALUE_UINT = 3,
    MPJ_VALUE_FLOAT = 4,
    MPJ_VALUE_STRING = 5,
    MPJ_VALUE_BINARY = 6,
    MPJ_VALUE_ARRAY = 7,
    MPJ_VALUE_MAP = 8
};

const uint8_t *mpj_buffer_data(const mpj_buffer *buffer);
size_t mpj_buffer_size(const mpj_buffer *buffer);
void mpj_buffer_delete(mpj_buffer *buffer);

size_t mpj_type_count(void);
const char *mpj_type_name(size_t type_id);
int mpj_type_id(const char *type_name);
size_t mpj_field_count(int type_id);
const char *mpj_field_name(int type_id, size_t field_id);
const char *mpj_field_c_type(int type_id, size_t field_id);
int mpj_field_key_kind(int type_id, size_t field_id);
const char *mpj_field_key_string(int type_id, size_t field_id);
int64_t mpj_field_key_int(int type_id, size_t field_id);
void *mpj_new(int type_id);
int mpj_delete(int type_id, void *value);
mpj_buffer *mpj_pack_bytes(int type_id, const void *value);
int mpj_unpack_bytes(int type_id, const uint8_t *data, size_t size, void *out);

mpj_value *mpj_value_new_nil(void);
mpj_value *mpj_value_new_bool(int value);
mpj_value *mpj_value_new_int(int64_t value);
mpj_value *mpj_value_new_uint(uint64_t value);
mpj_value *mpj_value_new_float(double value);
mpj_value *mpj_value_new_number(double value);
mpj_value *mpj_value_new_string(const uint8_t *data, size_t size);
mpj_value *mpj_value_new_binary(const uint8_t *data, size_t size);
mpj_value *mpj_value_new_array(size_t size);
mpj_value *mpj_value_new_map(size_t size);
void mpj_value_free(mpj_value *value);
int mpj_value_array_set(mpj_value *array, size_t index, mpj_value *item);
int mpj_value_map_set(mpj_value *map, size_t index, mpj_value *key, mpj_value *value);
mpj_buffer *mpj_value_pack_bytes(const mpj_value *value);
mpj_value *mpj_value_unpack_bytes(const uint8_t *data, size_t size);
int mpj_value_kind(const mpj_value *value);
int mpj_value_bool(const mpj_value *value);
int64_t mpj_value_int(const mpj_value *value);
uint64_t mpj_value_uint(const mpj_value *value);
double mpj_value_float(const mpj_value *value);
double mpj_value_number(const mpj_value *value);
const uint8_t *mpj_value_data(const mpj_value *value);
size_t mpj_value_size(const mpj_value *value);
const mpj_value *mpj_value_array_get(const mpj_value *array, size_t index);
const mpj_value *mpj_value_map_key(const mpj_value *map, size_t index);
const mpj_value *mpj_value_map_value(const mpj_value *map, size_t index);

#ifdef __cplusplus
}
#endif

#endif
