/*
 * DO NOT EDIT!
 * Generated by msgpack-pjsekai dump.cs compiler version 0.4.0.
 * source: dump.cs
 */

#include <jni.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "msgpack-pjsekai-bridge.h"

static void throw_java_exception(JNIEnv *env, const char *class_name, const char *message) {
    jclass cls = (*env)->FindClass(env, class_name);
    if (cls) (*env)->ThrowNew(env, cls, message);
}

static int is_instance(JNIEnv *env, jobject object, const char *class_name) {
    jclass cls = (*env)->FindClass(env, class_name);
    return cls && (*env)->IsInstanceOf(env, object, cls);
}

static mpj_value *value_from_java(JNIEnv *env, jobject object);

static mpj_value *value_from_byte_array(JNIEnv *env, jbyteArray array) {
    jsize size = (*env)->GetArrayLength(env, array);
    jbyte *data = (*env)->GetByteArrayElements(env, array, NULL);
    if (!data) return NULL;
    mpj_value *out = mpj_value_new_binary((const uint8_t *)data, (size_t)size);
    (*env)->ReleaseByteArrayElements(env, array, data, JNI_ABORT);
    return out;
}

static mpj_value *value_from_string(JNIEnv *env, jstring string) {
    const char *data = (*env)->GetStringUTFChars(env, string, NULL);
    if (!data) return NULL;
    mpj_value *out = mpj_value_new_string((const uint8_t *)data, strlen(data));
    (*env)->ReleaseStringUTFChars(env, string, data);
    return out;
}

static mpj_value *value_from_map(JNIEnv *env, jobject map) {
    jclass map_cls = (*env)->FindClass(env, "java/util/Map");
    jmethodID size_mid = (*env)->GetMethodID(env, map_cls, "size", "()I");
    jmethodID entry_set_mid = (*env)->GetMethodID(env, map_cls, "entrySet", "()Ljava/util/Set;");
    jint size = (*env)->CallIntMethod(env, map, size_mid);
    mpj_value *out = mpj_value_new_map((size_t)size);
    jobject set = (*env)->CallObjectMethod(env, map, entry_set_mid);
    jclass iterable_cls = (*env)->FindClass(env, "java/lang/Iterable");
    jmethodID iterator_mid = (*env)->GetMethodID(env, iterable_cls, "iterator", "()Ljava/util/Iterator;");
    jobject iterator = (*env)->CallObjectMethod(env, set, iterator_mid);
    jclass iterator_cls = (*env)->FindClass(env, "java/util/Iterator");
    jmethodID has_next_mid = (*env)->GetMethodID(env, iterator_cls, "hasNext", "()Z");
    jmethodID next_mid = (*env)->GetMethodID(env, iterator_cls, "next", "()Ljava/lang/Object;");
    jclass entry_cls = (*env)->FindClass(env, "java/util/Map$Entry");
    jmethodID get_key_mid = (*env)->GetMethodID(env, entry_cls, "getKey", "()Ljava/lang/Object;");
    jmethodID get_value_mid = (*env)->GetMethodID(env, entry_cls, "getValue", "()Ljava/lang/Object;");
    size_t index = 0;
    while ((*env)->CallBooleanMethod(env, iterator, has_next_mid)) {
        jobject entry = (*env)->CallObjectMethod(env, iterator, next_mid);
        jobject key = (*env)->CallObjectMethod(env, entry, get_key_mid);
        jobject value = (*env)->CallObjectMethod(env, entry, get_value_mid);
        mpj_value_map_set(out, index++, value_from_java(env, key), value_from_java(env, value));
    }
    return out;
}

static mpj_value *value_from_collection(JNIEnv *env, jobject collection) {
    jclass collection_cls = (*env)->FindClass(env, "java/util/Collection");
    jmethodID size_mid = (*env)->GetMethodID(env, collection_cls, "size", "()I");
    jint size = (*env)->CallIntMethod(env, collection, size_mid);
    mpj_value *out = mpj_value_new_array((size_t)size);
    jclass iterable_cls = (*env)->FindClass(env, "java/lang/Iterable");
    jmethodID iterator_mid = (*env)->GetMethodID(env, iterable_cls, "iterator", "()Ljava/util/Iterator;");
    jobject iterator = (*env)->CallObjectMethod(env, collection, iterator_mid);
    jclass iterator_cls = (*env)->FindClass(env, "java/util/Iterator");
    jmethodID has_next_mid = (*env)->GetMethodID(env, iterator_cls, "hasNext", "()Z");
    jmethodID next_mid = (*env)->GetMethodID(env, iterator_cls, "next", "()Ljava/lang/Object;");
    size_t index = 0;
    while ((*env)->CallBooleanMethod(env, iterator, has_next_mid)) {
        jobject item = (*env)->CallObjectMethod(env, iterator, next_mid);
        mpj_value_array_set(out, index++, value_from_java(env, item));
    }
    return out;
}

static mpj_value *value_from_java(JNIEnv *env, jobject object) {
    if (!object) return mpj_value_new_nil();
    if (is_instance(env, object, "java/lang/Boolean")) {
        jclass cls = (*env)->FindClass(env, "java/lang/Boolean");
        jmethodID mid = (*env)->GetMethodID(env, cls, "booleanValue", "()Z");
        return mpj_value_new_bool((*env)->CallBooleanMethod(env, object, mid));
    }
    if (is_instance(env, object, "java/lang/Float") || is_instance(env, object, "java/lang/Double")) {
        jclass cls = (*env)->FindClass(env, "java/lang/Number");
        jmethodID mid = (*env)->GetMethodID(env, cls, "doubleValue", "()D");
        return mpj_value_new_float((*env)->CallDoubleMethod(env, object, mid));
    }
    if (is_instance(env, object, "java/lang/Number")) {
        jclass cls = (*env)->FindClass(env, "java/lang/Number");
        jmethodID mid = (*env)->GetMethodID(env, cls, "longValue", "()J");
        jlong value = (*env)->CallLongMethod(env, object, mid);
        return value >= 0 ? mpj_value_new_uint((uint64_t)value) : mpj_value_new_int((int64_t)value);
    }
    if (is_instance(env, object, "java/lang/String")) return value_from_string(env, (jstring)object);
    if ((*env)->IsInstanceOf(env, object, (*env)->FindClass(env, "[B"))) return value_from_byte_array(env, (jbyteArray)object);
    if (is_instance(env, object, "java/util/Map")) return value_from_map(env, object);
    if (is_instance(env, object, "java/util/Collection")) return value_from_collection(env, object);
    return mpj_value_new_nil();
}

static jobject java_from_value(JNIEnv *env, const mpj_value *value) {
    int kind = mpj_value_kind(value);
    if (kind == MPJ_VALUE_NIL || kind < 0) return NULL;
    if (kind == MPJ_VALUE_BOOL) {
        jclass cls = (*env)->FindClass(env, "java/lang/Boolean");
        jmethodID mid = (*env)->GetStaticMethodID(env, cls, "valueOf", "(Z)Ljava/lang/Boolean;");
        return (*env)->CallStaticObjectMethod(env, cls, mid, (jboolean)mpj_value_bool(value));
    }
    if (kind == MPJ_VALUE_INT || kind == MPJ_VALUE_UINT) {
        jclass cls = (*env)->FindClass(env, "java/lang/Long");
        jmethodID mid = (*env)->GetStaticMethodID(env, cls, "valueOf", "(J)Ljava/lang/Long;");
        jlong n = kind == MPJ_VALUE_INT ? (jlong)mpj_value_int(value) : (jlong)mpj_value_uint(value);
        return (*env)->CallStaticObjectMethod(env, cls, mid, n);
    }
    if (kind == MPJ_VALUE_FLOAT) {
        jclass cls = (*env)->FindClass(env, "java/lang/Double");
        jmethodID mid = (*env)->GetStaticMethodID(env, cls, "valueOf", "(D)Ljava/lang/Double;");
        return (*env)->CallStaticObjectMethod(env, cls, mid, (jdouble)mpj_value_float(value));
    }
    if (kind == MPJ_VALUE_STRING) {
        size_t size = mpj_value_size(value);
        const uint8_t *data = mpj_value_data(value);
        char *tmp = (char *)malloc(size + 1);
        if (!tmp) return NULL;
        memcpy(tmp, data, size);
        tmp[size] = '\0';
        jstring out = (*env)->NewStringUTF(env, tmp);
        free(tmp);
        return out;
    }
    if (kind == MPJ_VALUE_BINARY) {
        size_t size = mpj_value_size(value);
        const uint8_t *data = mpj_value_data(value);
        jbyteArray out = (*env)->NewByteArray(env, (jsize)size);
        if (out && size > 0) (*env)->SetByteArrayRegion(env, out, 0, (jsize)size, (const jbyte *)data);
        return out;
    }
    if (kind == MPJ_VALUE_ARRAY) {
        jclass cls = (*env)->FindClass(env, "java/util/ArrayList");
        jmethodID init = (*env)->GetMethodID(env, cls, "<init>", "(I)V");
        jmethodID add = (*env)->GetMethodID(env, cls, "add", "(Ljava/lang/Object;)Z");
        size_t size = mpj_value_size(value);
        jobject out = (*env)->NewObject(env, cls, init, (jint)size);
        for (size_t i = 0; i < size; ++i) (*env)->CallBooleanMethod(env, out, add, java_from_value(env, mpj_value_array_get(value, i)));
        return out;
    }
    if (kind == MPJ_VALUE_MAP) {
        jclass cls = (*env)->FindClass(env, "java/util/LinkedHashMap");
        jmethodID init = (*env)->GetMethodID(env, cls, "<init>", "(I)V");
        jmethodID put = (*env)->GetMethodID(env, cls, "put", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
        size_t size = mpj_value_size(value);
        jobject out = (*env)->NewObject(env, cls, init, (jint)size);
        for (size_t i = 0; i < size; ++i) (*env)->CallObjectMethod(env, out, put, java_from_value(env, mpj_value_map_key(value, i)), java_from_value(env, mpj_value_map_value(value, i)));
        return out;
    }
    return NULL;
}

JNIEXPORT jbyteArray JNICALL Java_io_github_sekaiworld_msgpackpjsekai_MsgpackPjsekai_packNative(JNIEnv *env, jclass cls, jobject map) {
    (void)cls;
    mpj_value *value = value_from_java(env, map);
    if (!value) { throw_java_exception(env, "java/lang/IllegalStateException", "MessagePack encode failed"); return NULL; }
    mpj_buffer *buffer = mpj_value_pack_bytes(value);
    mpj_value_free(value);
    if (!buffer) { throw_java_exception(env, "java/lang/IllegalStateException", "MessagePack encode failed"); return NULL; }
    size_t size = mpj_buffer_size(buffer);
    const uint8_t *data = mpj_buffer_data(buffer);
    jbyteArray out = (*env)->NewByteArray(env, (jsize)size);
    if (out && size > 0) (*env)->SetByteArrayRegion(env, out, 0, (jsize)size, (const jbyte *)data);
    mpj_buffer_delete(buffer);
    return out;
}

JNIEXPORT jobject JNICALL Java_io_github_sekaiworld_msgpackpjsekai_MsgpackPjsekai_unpackNative(JNIEnv *env, jclass cls, jbyteArray input) {
    (void)cls;
    jsize size = (*env)->GetArrayLength(env, input);
    jbyte *data = (*env)->GetByteArrayElements(env, input, NULL);
    if (!data) return NULL;
    mpj_value *value = mpj_value_unpack_bytes((const uint8_t *)data, (size_t)size);
    (*env)->ReleaseByteArrayElements(env, input, data, JNI_ABORT);
    if (!value) { throw_java_exception(env, "java/lang/IllegalStateException", "MessagePack decode failed"); return NULL; }
    jobject out = java_from_value(env, value);
    mpj_value_free(value);
    return out;
}
